// <auto-generated />
using AiControlCenter.ControlPlane.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiControlCenter.ControlPlane.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ControlPlaneDbContext))]
internal sealed class ControlPlaneDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("control_plane")
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("AiControlCenter.ControlPlane.Domain.Direction", direction =>
        {
            direction.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
            direction.Property<DateTimeOffset?>("ArchivedAt")
                .HasColumnType("timestamp with time zone").HasColumnName("archived_at");
            direction.Property<string>("Code").IsRequired().HasMaxLength(64)
                .HasColumnType("character varying(64)").HasColumnName("code");
            direction.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone").HasColumnName("created_at");
            direction.Property<string>("Description").HasMaxLength(1000)
                .HasColumnType("character varying(1000)").HasColumnName("description");
            direction.Property<string>("Icon").HasMaxLength(100)
                .HasColumnType("character varying(100)").HasColumnName("icon");
            direction.Property<string>("Name").IsRequired().HasMaxLength(100)
                .HasColumnType("character varying(100)").HasColumnName("name");
            direction.Property<int>("SortOrder").HasColumnType("integer").HasColumnName("sort_order");
            direction.Property<string>("Status").IsRequired().HasMaxLength(16)
                .HasColumnType("character varying(16)").HasColumnName("status");
            direction.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone").HasColumnName("updated_at");
            direction.Property<uint>("Version").IsConcurrencyToken().ValueGeneratedOnAddOrUpdate()
                .HasColumnType("xid").HasColumnName("xmin");
            direction.HasKey("Id");
            direction.HasIndex("ArchivedAt", "Status", "SortOrder", "Name", "Id")
                .HasDatabaseName("ix_directions_list");
            direction.HasIndex("Code").IsUnique().HasDatabaseName("ux_directions_code");
            direction.ToTable("directions", "control_plane", table =>
            {
                table.HasCheckConstraint(
                    "ck_directions_code_format",
                    "char_length(code) BETWEEN 2 AND 64 AND code ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                table.HasCheckConstraint(
                    "ck_directions_name_length",
                    "char_length(btrim(name)) BETWEEN 2 AND 100");
                table.HasCheckConstraint("ck_directions_sort_order", "sort_order >= 0 AND sort_order <= 100000");
                table.HasCheckConstraint("ck_directions_status", "status IN ('Inactive', 'Active')");
                table.HasCheckConstraint(
                    "ck_directions_timestamps",
                    "updated_at >= created_at "
                    + "AND (archived_at IS NULL OR archived_at BETWEEN created_at AND updated_at)");
            });
        });
#pragma warning restore 612, 618
    }
}
