// <auto-generated />
using System;
using AiControlCenter.ControlPlane.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiControlCenter.ControlPlane.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ControlPlaneDbContext))]
    partial class ControlPlaneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("control_plane")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiControlCenter.ControlPlane.Domain.AgentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DirectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("direction_id");

                    b.Property<string>("ExecutionType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("execution_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_agent_definitions_code");

                    b.HasIndex("DirectionId");

                    b.HasIndex("ArchivedAt", "Status", "DirectionId", "Name", "Id")
                        .HasDatabaseName("ix_agent_definitions_list");

                    b.ToTable("agent_definitions", "control_plane", t =>
                        {
                            t.HasCheckConstraint("ck_agent_definitions_code_format", "char_length(code) BETWEEN 2 AND 64 AND code ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("ck_agent_definitions_execution_type", "execution_type = 'Test'");

                            t.HasCheckConstraint("ck_agent_definitions_name_length", "char_length(btrim(name)) BETWEEN 2 AND 100");

                            t.HasCheckConstraint("ck_agent_definitions_status", "status IN ('Inactive', 'Active')");

                            t.HasCheckConstraint("ck_agent_definitions_timestamps", "updated_at >= created_at AND (archived_at IS NULL OR archived_at BETWEEN created_at AND updated_at)");
                        });
                });

            modelBuilder.Entity("AiControlCenter.ControlPlane.Domain.Direction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_directions_code");

                    b.HasIndex("ArchivedAt", "Status", "SortOrder", "Name", "Id")
                        .HasDatabaseName("ix_directions_list");

                    b.ToTable("directions", "control_plane", t =>
                        {
                            t.HasCheckConstraint("ck_directions_code_format", "char_length(code) BETWEEN 2 AND 64 AND code ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("ck_directions_name_length", "char_length(btrim(name)) BETWEEN 2 AND 100");

                            t.HasCheckConstraint("ck_directions_sort_order", "sort_order >= 0 AND sort_order <= 100000");

                            t.HasCheckConstraint("ck_directions_status", "status IN ('Inactive', 'Active')");

                            t.HasCheckConstraint("ck_directions_timestamps", "updated_at >= created_at AND (archived_at IS NULL OR archived_at BETWEEN created_at AND updated_at)");
                        });
                });

            modelBuilder.Entity("AiControlCenter.ControlPlane.Domain.AgentDefinition", b =>
                {
                    b.HasOne("AiControlCenter.ControlPlane.Domain.Direction", null)
                        .WithMany()
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agent_definitions_directions_direction_id");
                });
#pragma warning restore 612, 618
        }
    }
}
